const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  listThemes: () => ipcRenderer.invoke('themes:list'),
  newScriptFromTheme: (themeId) => ipcRenderer.invoke('scripts:new', { themeId }),
  openScript: () => ipcRenderer.invoke('scripts:open'),
  saveScript: (payload) => ipcRenderer.invoke('scripts:save', payload),
  loadSettings: () => ipcRenderer.invoke('settings:load'),
  saveSettings: (payload) => ipcRenderer.invoke('settings:save', payload),
  generateScriptFromBrief: (payload) => ipcRenderer.invoke('scripts:generate-from-brief', payload),
  fetchAssets: (payload) => ipcRenderer.invoke('assets:fetch', payload),
  openAssetWindow: () => ipcRenderer.invoke('asset-window:open'),
  onAssetSelected: (callback) => ipcRenderer.on('asset:selected', (_event, payload) => callback(payload)),
  chooseBackgroundFile: () => ipcRenderer.invoke('background:choose-file'),
  chooseBgmFile: () => ipcRenderer.invoke('bgm:choose-file'),
  chooseYoutubeClientSecrets: () => ipcRenderer.invoke('file:choose-json'),
  chooseYoutubeCredentials: () => ipcRenderer.invoke('file:choose-any'),
  openBgmWindow: () => ipcRenderer.invoke('bgm-window:open'),
  openTrendWindow: () => ipcRenderer.invoke('trend-window:open'),
  openSchedulerWindow: () => ipcRenderer.invoke('scheduler:open'),
  onBgmSelected: (callback) => ipcRenderer.on('bgm:selected', (_event, payload) => callback(payload)),
  onTrendSelected: (callback) => ipcRenderer.on('trend:selected', (_event, payload) => callback(payload)),
  openSettingsWindow: () => ipcRenderer.invoke('settings:open-window'),
  generateAudio: (payload) => ipcRenderer.invoke('audio:generate', payload),
  clearAudioCache: () => ipcRenderer.invoke('audio:clear'),
  describeTimeline: (payload) => ipcRenderer.invoke('timeline:describe', payload),
  generateVideo: (payload) => ipcRenderer.invoke('video:generate', payload),
  uploadVideo: (payload) => ipcRenderer.invoke('video:upload', payload),
  openOutputPath: (payload) => ipcRenderer.invoke('video:open-output', payload),
  getLatestVideo: () => ipcRenderer.invoke('video:get-latest'),
  listOutputs: () => ipcRenderer.invoke('video:list-outputs'),
  deleteOutput: (payload) => ipcRenderer.invoke('video:delete-output', payload),
  scheduler: {
    list: () => ipcRenderer.invoke('scheduler:list'),
    save: (tasks) => ipcRenderer.invoke('scheduler:save', tasks),
    runNow: (taskId) => ipcRenderer.invoke('scheduler:run-now', taskId),
    remove: (taskId) => ipcRenderer.invoke('scheduler:remove', taskId),
    openLog: (logPath) => ipcRenderer.invoke('scheduler:open-log', logPath),
  },
  fetchLlmTrends: (payload) => ipcRenderer.invoke('trends:fetch-llm', payload),
  openExternalLink: (url) => ipcRenderer.invoke('external:open', url),
  youtubeAuth: {
    runAuthTest: () => ipcRenderer.invoke('youtube:auth-test'),
    deleteCredentials: () => ipcRenderer.invoke('youtube:delete-creds'),
  },
  // Preview window
  openPreviewWindow: () => ipcRenderer.invoke('preview:open'),
  onPreviewUpdate: (callback) => ipcRenderer.on('preview:update', (_event, data) => callback(data)),
  onPreviewRequestFromMain: (callback) => ipcRenderer.on('preview:request-from-main', callback),
  onPreviewScriptUpdated: (callback) => ipcRenderer.on('preview:script-updated', (_event, script) => callback(script)),
  updateScriptFromPreview: (script) => ipcRenderer.invoke('preview:update-script', script),
  requestPreviewData: () => ipcRenderer.send('preview:request-data'),
  sendPreviewData: (data) => ipcRenderer.send('preview:send-data', data),
});

contextBridge.exposeInMainWorld('yaml', {
  stringify: (data) => ipcRenderer.sendSync('yaml:stringify', data),
  parse: (text) => ipcRenderer.sendSync('yaml:parse', text),
});
